logging.level: info
logging.metrics.enabled: false
logging.to_stderr: true
logging.to_files: false
logging.files:
  path: ./
  name: logbeat
  keepfiles: 7
  permissions: 0644

#=========================== Filebeat inputs =============================
filebeat.inputs:
  - type: filestream
    id: test-ck
    enabled: true
    paths:
      - /tmp/testck.log
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true

#================================ clickhouse output ======================
output.clickhouse:
  addr: ["10.45.11.35:9000"]
  username: default
  password: "123456"
  table: ck_test
  columns: ["id", "name", "created_at"]
